# Generated by Django 2.2.2 on 2021-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('address', models.CharField(max_length=300)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Joined time')),
                ('last_login', models.DateField(auto_now=True, verbose_name='Last loged in')),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('nid_number', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
