# Generated by Django 2.2.2 on 2021-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210911_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password2',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
