# Generated by Django 2.2.2 on 2021-08-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
    ]
